A major upgrade to v2.3.1 The libopenjp2.a is created from 30 C files and 35 header files. deleted:    raw.c deleted:    raw.h new file:   sparse_array.c new file:   sparse_array.h modified 12 C files and 13 header files.
Updated /home/devel/Ultibo_Projects/jpeg2000/src from
commit 57096325457f96d8cd07bd3af04fe81d7a2ba788 (HEAD, tag: v2.3.1)
Author: Antonin Descampe <antonin@gmail.com>
Date:   Tue Apr 2 14:45:15 2019 +0200

    update token for appveyor auto release
2 files were removed and 2 new files.
25 of the C & header files were modified.

~/Ultibo_Projects/jpeg2000/src $ ./compile_ultibo.sh
The word count here should be 22
the word count in /home/pi/jpeg-2000-test/bare-metal/openjp
when ./libbuild.sh is executed should be 22
 22  22 182 libopenjp2_obj.txt

~/Ultibo_Projects/jpeg2000/RPi2 $ ./libbuild.sh
dwtlift.c: In function 'decompress':
dwtlift.c:658:3: warning: implicit declaration of function 'octave_write_byte'; did you mean 'opj_write_tile'? [-Wimplicit-function-declaration]
   octave_write_byte(r_decompress_fn,r_decompress,da_x1*da_y1);
   ^~~~~~~~~~~~~~~~~
   opj_write_tile
when ./libbuild.sh is executed should be 23
 23  23 192 libdwtlift_obj.txt

With Lazarus IDE (Ultibo Edition) DWT_LIFT_RPi2.lpi Run/Clean up and Build.
md5sum kernel7.img
27b9a8da3189bf5d94611cfd2cc2b4cf  kernel7.img
-rwxr-xr-x 1 devel devel 3225052 Jul 31 05:09 kernel7.img

~/firmwar_for_ultibo/jpeg2000 $ tftp 192.168.1.245
tftp> binary
tftp> put lena_rgb_1024.bmp MyBitmap.bmp
Sent 3145850 bytes in 8.3 seconds
tftp> put 1024com testfile
Sent 24 bytes in 0.0 seconds
tftp> quit

~/Ultibo_Projects/jpeg2000/ultibo $ ~/tmp/openjpeg/build/bin/opj_compress -r 80,40,20,10,1 -i test_wr.bmp -o tt.j2k

[INFO] tile number 1 / 1
[INFO] Generated outfile tt.j2k
encode time: 3253 ms

~/tmp/openjpeg/build/bin/opj_decompress -l 1 -i tt.j2k -o test_wr80.bmp

[INFO] Start to read j2k main header (0).
[INFO] Main header has been correctly decoded.
[INFO] No decoded area parameters, set the decoded area to the whole image
[INFO] Header of tile 1 / 1 has been read.
[INFO] Generated Outfile test_wr80.bmp
decode time: 785 ms

~/tmp/openjpeg/build/bin/opj_decompress -l 2 -i tt.j2k -o test_wr60.bmp

[INFO] Start to read j2k main header (0).
[INFO] Main header has been correctly decoded.
[INFO] No decoded area parameters, set the decoded area to the whole image
[INFO] Header of tile 1 / 1 has been read.
[INFO] Generated Outfile test_wr60.bmp
decode time: 812 ms
~/tmp/openjpeg/build/bin/opj_decompress -l 5 -i tt.j2k -o test_wr1.bmp

[INFO] Start to read j2k main header (0).
[INFO] Main header has been correctly decoded.
[INFO] No decoded area parameters, set the decoded area to the whole image
[INFO] Header of tile 1 / 1 has been read.
[INFO] Generated Outfile test_wr1.bmp
decode time: 1178 ms