openjpeg files needed to create libopenjp2.a are now in the Ultibo_Projects/jpeg2000/src.
pi@mypi3-1:~/Ultibo_Projects/jpeg2000/src $ ls -la libopenjp2.a
-rw-r--r-- 1 pi pi 388946 May 26 13:54 libopenjp2.a

The object that are part of the libopenjp2.a are found in the
file libopenjp2_obj.txt

pi@mypi3-1:~/Ultibo_Projects/jpeg2000/src $ ./compile_ultibo.sh
The word count here should be 21
the word count in /home/pi/jpeg-2000-test/bare-metal/openjp
when ./libbuild.sh is executed should be 22
 21  21 161 libopenjp2_obj.txt

pi@mypi3-1:~/Ultibo_Projects/jpeg2000/RPi2 $ ./libbuild.sh
dwtlift.c: In function 'decompress':
dwtlift.c:658:3: warning: implicit declaration of function 'octave_write_byte' [-Wimplicit-function-declaration]
   octave_write_byte(r_decompress_fn,r_decompress,da_x1*da_y1);
   ^
Adds the dwtlift.o to libopenjp2.a to create libdwtlift.a
void lift_config(int dec, int enc, int TCP_DISTORATIO, int FILTER, int CR, int flg, int bp, long imgsz,long him,long wim, int *bufferptr)
int decompress(int da_x0, int da_y0, int da_x1, int da_y1,const char *input_file)